### PR TITLE
Space out sponsor logos better

### PR DESCRIPTION
**Pull request by jaxbot**
screen shot 2015-12-22 at 11 43 09 pm

screen shot 2015-12-22 at 11 43 17 pm

### CODE REVIEW

**Comment by iveysaur** [comment]
im so sorry but 
image
this is an issue

**Comment by iveysaur** [comment]
due to screen resizing, viewpost looks the same as google/deloitte. Not sure what to do about that though

**Comment by maxcell** [comment]
Interesting, @iveysaur is that in Safari?
screen shot 2015-12-22 at 5 49 02 pm

**Comment by iveysaur** [comment]
thats from his screenshot lol

**Comment by iveysaur** [comment]
def better. Is it easier to continue doing this shrinking thing to keep things the right size or should we add like dividers or something? (not necessarily this merge but)

**Pull request merged**
